# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6f74d2c1-f284-40d5-8c69-e9e7fa040e34'
  imageRepository: 'ammugovprofilecicd'
  containerRegistry: 'akscontainer1234.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfiles'
  tag: '$(Build.BuildId)'



stages:
  -  stage: Build
     jobs:
       -  job: 
          steps:                       
           - task: Docker@0
             inputs:
               azureSubscription: $(Subscription)
               containerregistrytype: Container Registry             
               dockerRegistryConnection: $(dockerRegistryServiceConnection)
               action: Build an image
               dockerFile: '$(dockerfilePath)/app/Dockerfile'
               imageName: Vprofile-Application
               includeLatestTag: true
           - task: Docker@0
             inputs:
                azureSubscription: $(Subscription)
                containerregistrytype: Container Registry            
                dockerRegistryConnection: $(dockerRegistryConnection)           
                azureContainerRegistry: $(azureContainerRegistry)
                action: Push an image
                imageName:  Vprofile-Application
                includeLatestTag: true
              
              