trigger:
- main

variables:
   dockerRegistryConnection: :'akscontainer1234'
   Subscription: Free Trial(52d46f25-b0f2-46f2-b8b9-d3648b186f27)
   azureContainerRegistry: 'myacrrepo1212'
   dockerfilePath: '$(Build.SourcesDirectory)/Dockerfiles'

pool:
  name: Default

stages:
  -  stage: Build
     jobs:
       -  job: 
          steps:                       
           - task: Docker@0
             inputs:
               azureSubscription: $(Subscription)
               containerregistrytype: Container Registry             
               dockerRegistryConnection: $(dockerRegistryConnection)
               action: Build an image
               dockerFile: '$(dockerfilePath)/app/Dockerfile'
               imageName: Vprofile-Application
               includeLatestTag: true
           - task: Docker@0
             inputs:
                azureSubscription: $(Subscription)
                containerregistrytype: Container Registry            
                dockerRegistryConnection: $(dockerRegistryConnection)           
                azureContainerRegistry: $(azureContainerRegistry)
                action: Push an image
                imageName:  Vprofile-Application
                includeLatestTag: true